In [7]:
import pandas as pd
import numpy as np 
# from sklearn.svm import SVC
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score

In [8]:
df = pd.read_csv("Crop_recommendation.csv")

In [9]:
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [14]:
y  = np.array(df.iloc[:,-1])

In [15]:
print(y)

['rice' 'rice' 'rice' ... 'coffee' 'coffee' 'coffee']


In [65]:
df.label = df.label.apply(lambda x: label_dict[x])

In [66]:
df.label

0        0
1        0
2        0
3        0
4        0
        ..
2195    21
2196    21
2197    21
2198    21
2199    21
Name: label, Length: 2200, dtype: int64

In [67]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]


In [68]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [69]:
model = SVC(probability = True)

In [70]:
model.fit(X_train, y_train)

SVC(probability=True)

In [71]:
y_test

830      8
1059    10
484      4
27       0
2088    20
        ..
217      2
1915    19
412      4
1302    13
314      3
Name: label, Length: 550, dtype: int64

In [76]:
model.predict_proba(X_test)[0]

array([0.0010954 , 0.00538657, 0.00196596, 0.00256514, 0.00527132,
       0.00278448, 0.00434867, 0.01745658, 0.93120291, 0.00191255,
       0.00319739, 0.00214965, 0.00108418, 0.00203923, 0.00205158,
       0.0010129 , 0.00186658, 0.00624945, 0.00127984, 0.00256654,
       0.00125192, 0.00126116])

In [1]:
label_dict[model.predict(X_test)[0]]

NameError: name 'label_dict' is not defined

In [74]:
y_train.unique()

array([ 2, 14, 15, 12, 18,  8, 19, 20, 16, 11,  3, 21,  7,  6,  1, 10, 17,
       13,  0,  5,  9,  4], dtype=int64)

In [75]:
df['label'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21], dtype=int64)